# Generated by Django 4.1.7 on 2023-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('cost', models.FloatField()),
                ('release_date', models.DateField()),
                ('description', models.TextField(max_length=5000)),
                ('averagerating', models.FloatField(default=0)),
                ('photo', models.URLField(default=None, null=True)),
            ],
        ),
    ]
